# Generated by ChatGPT on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("aic", "Art Institute of Chicago"), ("serp", "SerpApi Google Events")], max_length=20)),
                ("source_event_id", models.CharField(blank=True, max_length=255, null=True)),
                ("event_key", models.CharField(max_length=512, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("museum", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("time_display", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("ticket_from", models.FloatField(default=20)),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_date", "title"],
            },
        ),
    ]
